### ISSUE TITLE
Unsupported inverter Type 702

### ISSUE THREAD

**Issue by bruecknerdaniel** [HAEdwin/homeassistant-apsystems_ecur#1]
Hi all,

When I try to install the integration and specify the IP address of the ECU-B, I get the message ```Can't connect to ECU. Please check log```.

Here's the log:

```
2022-08-18 20:54:30.964 ERROR (MainThread) [custom_components.apsystems_ecur.config_flow] APSystemsInvalidData exception: Unsupported inverter type 702 please create GitHub issue.
Traceback (most recent call last):
  File "/config/custom_components/apsystems_ecur/config_flow.py", line 45, in async_step_user
    test_query = await self.hass.async_add_executor_job(ap_ecu.query_ecu)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/apsystems_ecur/APSystemsSocket.py", line 158, in query_ecu
    data = self.process_inverter_data()
  File "/config/custom_components/apsystems_ecur/APSystemsSocket.py", line 348, in process_inverter_data
    raise APSystemsInvalidData(error)
custom_components.apsystems_ecur.APSystemsSocket.APSystemsInvalidData: Unsupported inverter type 702 please create GitHub issue.

```

I have two DS3-S (IDs start with 702) connected to my ECU-B.

Can you please give me support?

**Comment by bruecknerdaniel** [comment]
Sorry. Found the solution here:

https://github.com/ksheumaker/homeassistant-apsystems_ecur/issues/85

**Comment by HAEdwin** [comment]
@bruecknerdaniel No problem, we really need an update on the main branch of @ksheumaker. Issue closed.
